export const RESERVATION_GET_LOCATIONS = 'RESERVATION_GET_LOCATIONS';
export const RESERVATION_GET_LOCATIONS_SUCCESS = 'RESERVATION_GET_LOCATIONS_SUCCESS';
export const RESERVATION_GET_LOCATIONS_FAIL = 'RESERVATION_GET_LOCATIONS_FAIL';
export const RESERVATION_GET_LOCATIONS_ERROR = 'RESERVATION_GET_LOCATIONS_ERROR';

export const RESERVATION_GET_ALL = 'RESERVATION_GET_ALL';
export const RESERVATION_GET_ALL_SUCCESS = 'RESERVATION_GET_ALL_SUCCESS';
export const RESERVATION_GET_ALL_FAIL = 'RESERVATION_GET_ALL_FAIL';
export const RESERVATION_GET_ALL_ERROR = 'RESERVATION_GET_ALL_ERROR';

export const RESERVATION_CHANGE_STATUS = 'RESERVATION_CHANGE_STATUS';
export const RESERVATION_CHANGE_STATUS_SUCCESS = 'RESERVATION_CHANGE_STATUS_SUCCESS';
export const RESERVATION_CHANGE_STATUS_FAIL = 'RESERVATION_CHANGE_STATUS_FAIL';
export const RESERVATION_CHANGE_STATUS_ERROR = 'RESERVATION_CHANGE_STATUS_ERROR';
