export const RESERVATION_GET_ALL = 'RESERVATION_GET_ALL';
export const RESERVATION_GET_ALL_SUCCESS = 'RESERVATION_GET_ALL_SUCCESS';
export const RESERVATION_GET_ALL_FAIL = 'RESERVATION_GET_ALL_FAIL';
export const RESERVATION_GET_ALL_ERROR = 'RESERVATION_GET_ALL_ERROR';
